// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tsgraph.proto

package ppb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TSGraph struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Point                []*Point `protobuf:"bytes,2,rep,name=point,proto3" json:"point,omitempty"`
	Edge                 []*Edge  `protobuf:"bytes,3,rep,name=edge,proto3" json:"edge,omitempty"`
	Places               []string `protobuf:"bytes,4,rep,name=places,proto3" json:"places,omitempty"`
	Labels               []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Types                []string `protobuf:"bytes,6,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TSGraph) Reset()         { *m = TSGraph{} }
func (m *TSGraph) String() string { return proto.CompactTextString(m) }
func (*TSGraph) ProtoMessage()    {}
func (*TSGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98ba1d02d466827, []int{0}
}

func (m *TSGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TSGraph.Unmarshal(m, b)
}
func (m *TSGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TSGraph.Marshal(b, m, deterministic)
}
func (m *TSGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TSGraph.Merge(m, src)
}
func (m *TSGraph) XXX_Size() int {
	return xxx_messageInfo_TSGraph.Size(m)
}
func (m *TSGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_TSGraph.DiscardUnknown(m)
}

var xxx_messageInfo_TSGraph proto.InternalMessageInfo

func (m *TSGraph) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TSGraph) GetPoint() []*Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *TSGraph) GetEdge() []*Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

func (m *TSGraph) GetPlaces() []string {
	if m != nil {
		return m.Places
	}
	return nil
}

func (m *TSGraph) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *TSGraph) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type Point struct {
	Place                int32    `protobuf:"varint,1,opt,name=place,proto3" json:"place,omitempty"`
	Time                 int32    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Label                int32    `protobuf:"varint,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98ba1d02d466827, []int{1}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetPlace() int32 {
	if m != nil {
		return m.Place
	}
	return 0
}

func (m *Point) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Point) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Point) GetLabel() int32 {
	if m != nil {
		return m.Label
	}
	return 0
}

type Edge struct {
	FromPoint            int32     `protobuf:"varint,1,opt,name=from_point,json=fromPoint,proto3" json:"from_point,omitempty"`
	ToPoint              int32     `protobuf:"varint,2,opt,name=to_point,json=toPoint,proto3" json:"to_point,omitempty"`
	Type                 int32     `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Label                int32     `protobuf:"varint,4,opt,name=label,proto3" json:"label,omitempty"`
	Weight               []float64 `protobuf:"fixed64,5,rep,packed,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98ba1d02d466827, []int{2}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetFromPoint() int32 {
	if m != nil {
		return m.FromPoint
	}
	return 0
}

func (m *Edge) GetToPoint() int32 {
	if m != nil {
		return m.ToPoint
	}
	return 0
}

func (m *Edge) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Edge) GetLabel() int32 {
	if m != nil {
		return m.Label
	}
	return 0
}

func (m *Edge) GetWeight() []float64 {
	if m != nil {
		return m.Weight
	}
	return nil
}

func init() {
	proto.RegisterType((*TSGraph)(nil), "ppb.TSGraph")
	proto.RegisterType((*Point)(nil), "ppb.Point")
	proto.RegisterType((*Edge)(nil), "ppb.Edge")
}

func init() { proto.RegisterFile("tsgraph.proto", fileDescriptor_f98ba1d02d466827) }

var fileDescriptor_f98ba1d02d466827 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xc6, 0x6e, 0xc9, 0x21, 0x16, 0x0b, 0x21, 0x33, 0x54, 0x8a, 0x32, 0x65, 0xca,
	0x00, 0xbf, 0x01, 0xb1, 0x22, 0xc3, 0xc6, 0x50, 0x25, 0xf4, 0x48, 0x23, 0x25, 0xf5, 0x29, 0xb1,
	0x84, 0xb2, 0xf2, 0x5b, 0xf8, 0xa1, 0xe8, 0xee, 0xca, 0xce, 0xe6, 0xf7, 0x3d, 0x5f, 0xde, 0xbb,
	0x18, 0x6e, 0xd2, 0xd2, 0xcf, 0x2d, 0x9d, 0x1a, 0x9a, 0x63, 0x8a, 0x2e, 0x27, 0xea, 0xaa, 0x9f,
	0x0c, 0x76, 0x6f, 0xaf, 0xcf, 0x8c, 0x9d, 0x03, 0x73, 0x6e, 0x27, 0xf4, 0x59, 0x99, 0xd5, 0x45,
	0x90, 0xb3, 0x2b, 0xc1, 0x52, 0x1c, 0xce, 0xc9, 0x6f, 0xca, 0xbc, 0xbe, 0x7e, 0x80, 0x86, 0xa8,
	0x6b, 0x5e, 0x98, 0x04, 0x35, 0xdc, 0x1e, 0x0c, 0x1e, 0x7b, 0xf4, 0xb9, 0x5c, 0x28, 0xe4, 0xc2,
	0xd3, 0xb1, 0xc7, 0x20, 0xd8, 0xdd, 0xc1, 0x96, 0xc6, 0xf6, 0x03, 0x17, 0x6f, 0xca, 0xbc, 0x2e,
	0xc2, 0x45, 0x31, 0x1f, 0xdb, 0x0e, 0xc7, 0xc5, 0x5b, 0xe5, 0xaa, 0xdc, 0x2d, 0xd8, 0xb4, 0x12,
	0x2e, 0x7e, 0x2b, 0x58, 0x45, 0xf5, 0x0e, 0x56, 0x42, 0xd9, 0x96, 0x0f, 0x48, 0x49, 0x1b, 0x54,
	0x70, 0xf3, 0x34, 0x4c, 0xe8, 0x37, 0x02, 0xe5, 0x2c, 0x6c, 0x25, 0xee, 0xa5, 0x6c, 0x25, 0xe4,
	0x69, 0x89, 0xf1, 0x46, 0xa7, 0x45, 0x54, 0xdf, 0x19, 0x18, 0x6e, 0xec, 0xf6, 0x00, 0x9f, 0x73,
	0x9c, 0x0e, 0xba, 0xb1, 0x26, 0x14, 0x4c, 0x34, 0xfb, 0x1e, 0xae, 0x52, 0x3c, 0xfc, 0xfd, 0x0e,
	0x36, 0x77, 0x29, 0xaa, 0xf5, 0xef, 0x30, 0xde, 0xfb, 0x0b, 0x87, 0xfe, 0x94, 0x64, 0xef, 0x2c,
	0x5c, 0x54, 0xb7, 0x95, 0x47, 0x79, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x0d, 0xed, 0x37,
	0xa5, 0x01, 0x00, 0x00,
}
